### ISSUE TITLE
file_handle.write does not append

### ISSUE THREAD

**Issue by aep** [gluster/Gfapi-sys#23]
Hi,

i have no experience with the c api, and there appears to be no documentation. the link in the readme is down.

when experimenting with the example in gfapi-sys, i noticed that file_handle.write does write from file offset 0 instead of append to the file, as O_APPEND would suggest. 

```
      for _ in 0..1000 {
          let mut m1 : [u8;1024*1024] = [0;1024*1024];
          ur.read_exact(&mut m1).expect("cannot read /dev/urandom");
  
          now = Instant::now();
          match file_handle.write(&m1, O_APPEND) {
              Ok(bytes_written) => {
                  let mut el = now.elapsed().as_nanos();
                  if el == 0 { 
                      el = 1 
                  }   
                  println!("Wrote {} bytes in {} ms. that's {} b/ms", bytes_written, el, (bytes_written as u128)/el);
              }   
              Err(e) => {
                  println!("writing to file failed: {:?}", e); 
                  return;
              }   
          };  
      } 
```

**Comment by cholcombe973** [comment]
Yeah the C documentation for gluster is basically non existent. The easiest thing to reference is the linux manpages which the gluster C api should mirror more or less. It's a posix interface after all. 
That's interesting that `O_APPEND` doesn't actually append. What version of glusterfs are you using?

**Comment by aep** [comment]
its gluster 9.3

but i think the issue is here https://github.com/gluster/Gfapi-sys/blob/master/src/gluster.rs#L1000

    pub fn write(&self, buffer: &[u8], flags: i32) -> Result<isize, GlusterError> {
        self.pwrite(buffer, buffer.len(), 0, flags)

it uses pwrite with offset to 0 instead of write

**Comment by cholcombe973** [comment]
Yup that looks like the issue. Would you like to PR it?

**Comment by aep** [comment]
yeah, will do later.
